language: android

android:
  components:
    # Update tools and then platform-tools explicitly so lint gets an updated database. Can be removed once 3.0 is out.
    - tools
    - platform-tools
    - sys-img-armeabi-v7a-android-18

jdk:
  - oraclejdk8

before_script:
    # Install SDK license so Android Gradle plugin can install deps.
    - mkdir "$ANDROID_HOME/licenses" || true
    - echo "8933bad161af4178b1185d1a37fbf41ea5269c55\nd56f5187479451eabf01fb78af6dfcb131a6481e" > "$ANDROID_HOME/licenses/android-sdk-license"

script: ./gradlew clean test

branches:
  except:
    - gh-pages

notifications:
  email: false

sudo: false

before_cache:
    - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle
