title: FastAdapter
description: The bullet proof, fast and easy to use adapter library, which minimizes developing time to a fraction...
google_analytics: UA-56332427-1
show_downloads: true
theme: jekyll-theme-minimal

gems:
  - jekyll-mentions
